version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mondi
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: devops/deploy/ApplicationStop.sh
      runas: ec2-user
  BeforeInstall:
    - location: devops/deploy/BeforeInstall.sh
      runas: ec2-user
  AfterInstall:
    - location: devops/deploy/AfterInstall.sh
      runas: ec2-user
  ApplicationStart:
    - location: devops/deploy/ApplicationStart.sh
      runas: ec2-user
